# Generated by Django 2.2.10 on 2021-11-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_API_app', '0002_auto_20210826_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
